apiVersion: v1
kind: Service
metadata:
  name: test-ext-svc
spec:
  type: NodePort
  selector:
    app: test-ext-app
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-int-svc
spec:
  type: ClusterIP
  selector:
    app: test-int-app
  ports:
  - name: http
    port: 80
    targetPort: 80
