apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  ports:
    - name: webport
      port: 9000        # 서비스 포트
      targetPort: 8080  # 목적지 파드 포트
  selector:
    app: deploy-websrv
  type: NodePort
